### ISSUE TITLE
Failure to read RRD files when rrdtool is invoked thousands of times in a loop (v0.1.5)

### ISSUE THREAD

**Issue by palisadoes** [commx/python-rrdtool#11]
I've been using your `rrdtool` library for some time. On systems running Ubuntu 14.04.4 LTS and rrdtool v0.1.1. reading 1000+ files for data, it works flawlessly.

On Ubuntu 16.04.1 LTS it works flawlessly on v0.1.1 for the same files, but gets the following intermittent errors on v0.1.5.

The code I'm using is below, where `filename` is the RRD filename and `start_at` is UTC time.

`results = rrdtool.fetch(filename, 'MAX', '-s', start_at, '-e', 'now')`

In version 0.1.5 I get the following errors:

```
Traceback: Traceback (most recent call last):
  File "/mysterious/rrd_reader.py", line 579, in get_rrd_data
    filename, 'MAX', '-s', start_at, '-e', 'now')
rrdtool.OperationalError: Usage: rrdtool fetch <file> <CF> [options]

Traceback: Traceback (most recent call last):
  File "/mysterious/rrd_reader.py", line 579, in get_rrd_data
    filename, 'MAX', '-s', start_at, '-e', 'now')
rrdtool.OperationalError: Usage: rrdtool (null) <file> <CF> [options]

Traceback (most recent call last):
  File "/mysterious/rrd_reader.py", line 579, in get_rrd_data
    filename, 'MAX', '-s', start_at, '-e', 'now')
rrdtool.OperationalError

Traceback: Traceback (most recent call last):
  File "/mysterious/rrd_reader.py", line 579, in get_rrd_data
    filename, 'MAX', '-s', start_at, '-e', 'now')
rrdtool.OperationalError: unknown consolidation function '1474497600'
```

Sometimes it doesn't recognize the timestamp, other times it doesn't seem to know I'm doing a `fetch` and messages `(null)` instead.

The errors are repeatable by just upgrading to v0.1.5 on Ubuntu 16.04.1 LTS. They go away when downgraded to v0.1.1

Typically no more than 20 minutes of 300s RRD step data is read per RRD file as the script runs three times per hour.

The script also sometimes fails with a segmentation fault on the newer code like this. Works perfectly on the older v0.1.1 code.

```
Segmentation fault (core dumped)
```

**Comment by commx** [comment]
Hi,

can you please provide some example code that triggers the bug? I've tested with a few thousand iterations to call fetch, but the error hasn't been raised since. Please also provide the Python version you're using.

**Comment by palisadoes** [comment]
I'll try to create a subset of the code. However it seems to be triggered when running pools of threads or sub-processes each accessing a separate RRD file. In our case we have seen the issue when accessing a directory with thousands of RRD files in a directory.

**Comment by commx** [comment]
You might try using v0.1.4 and let me know if that one works or not.

0.1.5 includes an upstream patch that allows the GIL to be released for I/O bound operations. It will release the GIL calling the librrd functions so other threads will not block until the function is completed.

**Comment by palisadoes** [comment]
Tested using rrdtool (0.1.11) for the past couple hours without repeating the issue.
