### ISSUE TITLE
Python3 bindings are not installed with pip

### ISSUE THREAD

**Issue by kpeletidis** [commx/python-rrdtool#13]
Hi,

I installed rrdtool using pip:

```
$ pip install rrdtool
Requirement already satisfied (use --upgrade to upgrade): rrdtool in /usr/local/lib/python2.7/dist-packages
```

But as you can see above only the python2 bindings are installed. Both python2 and python3 are installed on the system. Any suggestions? Thanks.

More system information:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

$ uname -a
Linux mavros 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by commx** [comment]
Try using `pip3 install rrdtool` as the default pip on Ubuntu is for Python 2.7. If pip3 is not available, you may install the package python3-pip first.

**Comment by kpeletidis** [comment]
It worked, thanks :-)
