### ISSUE TITLE
version 0.1.8 does not compile on machines using a default dialect older than c99 (tested on CentOS 7)

### ISSUE THREAD

**Issue by m3t4lukas** [commx/python-rrdtool#15]
Here is the pip console output:
[rrdtool compile error.txt](https://github.com/commx/python-rrdtool/files/588610/rrdtool.compile.error.txt)

I hope that helps.

Edit: when changing gcc default behavior by generating and editing the spec file it compiles without any complaints.

**Comment by commx** [comment]
v0.1.9 has been released to address this bug. Thanks for reporting!
