### ISSUE TITLE
Pypi package missing "rrdtoolmodule.h"

### ISSUE THREAD

**Issue by jinm** [commx/python-rrdtool#17]
The 0.1.10 package released to pypi at https://pypi.python.org/pypi/rrdtool/0.1.10 does not have "rrdtoolmodule.h" included. Can someone please help? Thanks.

**Comment by commx** [comment]
Hi,
indeed the source distribution was lacking the header file. 0.1.11 has been released to address this.

**Comment by jinm** [comment]
Looks good. Thank you!
