### ISSUE TITLE
unable to install on x64

### ISSUE THREAD

**Issue by kecksk0enig** [commx/python-rrdtool#2]
easy_install rrdtool
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Searching for rrdtool
Reading https://pypi.python.org/simple/rrdtool/
Best match: rrdtool 0.1.1
Downloading https://pypi.python.org/packages/source/r/rrdtool/rrdtool-0.1.1.tar.gz#md5=7aa3e68728f21c21ff66bb8176a46ec3
Processing rrdtool-0.1.1.tar.gz
Writing /tmp/easy_install-00j8i4/rrdtool-0.1.1/setup.cfg
Running rrdtool-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-00j8i4/rrdtool-0.1.1/egg-dist-tmp-iTQN1z
rrdtoolmodule.c:26:17: fatal error: rrd.h: Datei oder Verzeichnis nicht gefunden
 #include <rrd.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by adam1book** [comment]
You need to install the package librrd-dev. This should fix the missing rrd.h problem. This has nothing to do with 64-bit vs. 32-bit Linux. I'm not sure why this wasn't a dependency.
