### ISSUE TITLE
Segfault while creating database

### ISSUE THREAD

**Issue by LongHairedHacker** [commx/python-rrdtool#23]
Running the following code (which is just the example from the README) I get a segfault.

```python
#!/usr/bin/env python3

import rrdtool

# Create Round Robin Database
rrdtool.create('test.rrd', '--start', 'now', '--step', '300',
               'RRA:AVERAGE:0.5:1:1200',
               'DS:temp:GAUGE:600:-273:5000')

# Feed updates to the RRD
rrdtool.update('test.rrd', 'N:32')
```
I ran the python interpreter in gdb and got the following:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff65e52a7 in convert_args (
    command=command@entry=0x7ffff65e774a "create", args=0x7ffff7ed85f8, 
    rrdtool_argv=rrdtool_argv@entry=0x7fffffffde20, 
    rrdtool_argc=rrdtool_argc@entry=0x7fffffffde1c) at rrdtoolmodule.c:160
160	rrdtoolmodule.c: No such file or directory.
```

Any ideas on what went wrong there?

Versions:
RRDtool 1.7.0
Python 3.6.4
python-rrdtool 0.1.13

**Comment by commx** [comment]
Hi, please test the latest release v0.1.14 (6826a6c3) if it fixes the issue for you:

`pip install rrdtool==0.1.14`

**Comment by LongHairedHacker** [comment]
Okay v0.1.14 works for me.

Thanks for the quick response and let me know if you need any additional information.

**Comment by commx** [comment]
I'll add further tests to address this type of issues in the future. Thanks for reporting.
