### ISSUE TITLE
Graphs not smooth when updated using rrdtool.update

### ISSUE THREAD

**Issue by tanshaoyi** [commx/python-rrdtool#26]
Hi,

It looks like the update function results in lines that are not smooth.

I am using the rrdtool.update function with the following arguments:

rrdtool.update(dfile, '--daemon', RRDCACHEDSOCK, 'N:'+str(bytesreceived)+':'+str(bytessent))

Lines appear smooth though if they are updated via the command line:

subprocess.check_output([RRDTOOL, 'update', dfile, '--daemon', RRDCACHEDSOCK,
'N:'+str(bytesreceived)+':'+str(bytessent)])

(ie, I am using the same script with the same arguments to update the RRD).

Is there something I am doing wrong?

Thanks.
![getbw php-80](https://user-images.githubusercontent.com/46879343/51450993-10625a80-1d6e-11e9-92eb-f8f4993e0a0d.png)

**Comment by commx** [comment]
The "smoothness" of graphs has nothing to do with feeding data into the database. In fact, the module wraps pythonic calls directly to internal rrdtool functions; it may be possible that the rrdtool binary and the linked library may have different versions. The time and values are exactly the same in both provided methods.
