### ISSUE TITLE
Should have librrd-dev added as a dependency

### ISSUE THREAD

**Issue by adam1book** [commx/python-rrdtool#3]
The package librrd-dev should be added as a dependency, otherwise installation fails with a message saying rrd.h is missing.

**Comment by commx** [comment]
At this time there is no way to detect whether librrd is installed using setuptools in a reliable manner. rrdtool must be installed prior installing/building the bindings (make sure to have the headers in the standard header location paths).

**Comment by user2589** [comment]
@adam1book ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/commx/python-rrdtool/issues/3)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
