### ISSUE TITLE
Trend / Prediction with python-rrdtool

### ISSUE THREAD

**Issue by 3c2b2ff5** [commx/python-rrdtool#33]
Hi,

is it possible to create trends / prediction with the tool? Something similar to [this](http://hints.jeb.be/2009/12/04/trend-prediction-with-rrdtool/)?

Thanks a lot

**Comment by commx** [comment]
Hi,

sure. python-rrdtool wraps its calls to rrdtool internals, so passing the same arguments to the [graph](https://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html) method should give you what you want.

```python
import rrdtool

rrdtool.graph(
    "MEMORY_Trend.png",
    "--start", "now-7d",
    "--end", "now",
    "DEF:…",
    # and so on
)
```

Please note, this is not an issue but more like a general rrdtool question. Feel free to post it into official [rrdtool mailing lists](http://rrd-mailinglists.937164.n2.nabble.com/) to get support from the community.

**Comment by 3c2b2ff5** [comment]
Thank you very much for the quick reply. I'll post it in the mailing list.
