### ISSUE TITLE
Python Wheels

### ISSUE THREAD

**Issue by dgomes** [commx/python-rrdtool#36]
**Describe the bug**
This is not really a bug, but we could use Python Wheels as part of python-rrdtool distribution

**Comment by dgomes** [comment]
Maybe using https://github.com/pypa/python-manylinux-demo ?

**Comment by commx** [comment]
Hi, there are no plans to provide wheels because the library depends on external binary libraries and those need to be present on the target system to build the extension. We'd like to keep it simple.
