### ISSUE TITLE
Where is HAVE_RRD_GRAPH defined?

### ISSUE THREAD

**Issue by denilsonsa** [commx/python-rrdtool#5]
I have Lubuntu 15.04, with `librrd-dev` package already installed.

I used a Python 2.7 virtualenv and then tried installing this module using `pip install rrdtool`. The resulting module, however, did not have `graph` support.

I then manually cloned the repository, manually edited the C source file to include `#define HAVE_RRD_GRAPH`, and then used `setup.py` to build and install it in the virtualenv. The module worked fine afterwards, WITH `graph` support.

So… Where is `HAVE_RRD_GRAPH` defined? After a quick look, I believe it gets defined only in `rrd_config.h`, which is only available during the compilation of `rrdtool`, which means this C definition is not exported anywhere. If this is the case, maybe we should open an issue at https://github.com/oetiker/rrdtool-1.x asking to expose this definition. Alternatively, we can work around it in this module source code or in this module build logic.

**Comment by ferrarimarco** [comment]
@denilsonsa same issue here.

**Comment by bobdoah** [comment]
@denilsonsa Same issue on Debian 8, python 2.7.9 and `pip install rrdtool` in the global dist-packages

**Comment by commx** [comment]
0.1.3 is released.

The macro `HAVE_RRD_GRAPH` was not declared in most build environments, which prevented the appropriate graphing methods to be built. This has been fixed now.
