### ISSUE TITLE
"graph" functionality not showing up

### ISSUE THREAD

**Issue by l3u** [commx/python-rrdtool#7]
I installed python-rrdtool via the standard Gentoo ebuild way (cf. https://bugs.gentoo.org/show_bug.cgi?id=575582 for the ebuild). it works, but the "graph" functionality does not show up:

    >>> import rrdtool
    >>> dir(rrdtool)
    ['OperationalError', 'ProgrammingError', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'create', 'dump', 'fetch', 'first', 'flushcached', 'info', 'last', 'lastupdate', 'lib_version', 'resize', 'tune', 'update', 'updatev']

This is the case both for v0.1.2 and git master here. Does something "special" have to be done to get the "graph" function? Thanks for the help in advance :-)

**Comment by l3u** [comment]
I just found out that I have to add `#define HAVE_RRD_GRAPH` to the sources so that the graph functions are built. Do I have to patch the sources, depending on if or if not rrdtool has been built with the graph functionality or is there a way to know it from it's header files or something like that?

**Comment by commx** [comment]
I guess the ebuild uses version 0.1.2 of the binding, which indeed required the define in its header files. The latest version included a fix for that. I'd recommend installing the binding via pip, as it ensures that you're using the latest available version.

**Comment by l3u** [comment]
Okay ... I tried the same ebuild with git master, with the same result. However, I changed the ebuild (it's actually for v0.1.2, which is the latest tagged version) so that a patch addding `#define HAVE_RRD_GRAPH` is applied when it's built with a "graph" USE flag set (which then pulls rrdtool built with the "graph" USE flag as a dependency). Should be fine I guess ;-)

Thanks for the clarification!
