### ISSUE TITLE
python-rrdtool does not consider/pass the locale setting

### ISSUE THREAD

**Issue by l3u** [commx/python-rrdtool#8]
When creating a graph via python-rrdtool, the locale is apparently not passed. The resulting graph contains C locale month/day/etc names instead of the translated ones (e. g. I use a German locale here and get "Monday" instead of "Montag").

When rrdtool graph is called from a console directly, the translated strings are used here. Same if the "graph" call is replaced by subprocess.call (and of course, all arguments are listed in [ ] and 'rrdtool', 'graph' is prefixed).

Is this a bug or do I miss something?

Thanks for all Help!

**Comment by commx** [comment]
This is more a pythonic issue: The Python interpreter does not automatically apply the environment locale to it's internal localisation machinery.

Use the following code to get this fixed:

```python
import locale
import rrdtool

locale.setlocale(locale.LC_ALL, 'de_DE')
rrdtool.graph(…)
```

If you depend on using the locale as set by environment variables, you may use the following:

```python
import locale
import rrdtool

locale.setlocale(locale.LC_ALL, '')  # this will use the locale as set in the environment variables
rrdtool.graph(…)
