### ISSUE TITLE
Return graph as string

### ISSUE THREAD

**Issue by slavkoja** [commx/python-rrdtool#9]
In the original rrdtool it is possible to get the graph as string via the ``stdout``. This behavior is possible in ``python-rrdtool`` too when i pass the "-" as filename, but it returns the image via the ``stdout`` and not as return value. For now it is not possible (or not documented) how to get it as Python string, e.g.:
```python
image = rrdtool.graph(...)
# do something with image
```
Please, can you add this feature or describe how to do it?

**Comment by commx** [comment]
This can be done by using `graphv` instead:

```python
args = ['-', 'DEF:…', …]
data = rrdtool.graphv(*args)
image_bytes = data['image']
```
